require("items.apple")
-- require("items.menus")
require("items.spaces")
require("items.calendar")
require("items.battery")
require("items.wifi")
require("items.cpu")
require("items.media")
require("items.volume")
