#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# yabai -m config external_bar               all:40:0
yabai -m config mouse_follows_focus        off
yabai -m config focus_follows_mouse        on
yabai -m config window_zoom_persist        on
yabai -m config window_placement           second_child
yabai -m config window_shadow              float
yabai -m config window_opacity             on
yabai -m config window_opacity_duration    0.2
yabai -m config active_window_opacity      1.0
yabai -m config normal_window_opacity      0.96
yabai -m config window_animation_duration  0.5
yabai -m config window_animation_easing    ease_out_circ
yabai -m config insert_feedback_color      0xff9dd274
yabai -m config split_ratio                0.50
yabai -m config auto_balance               off
# yabai -m config menubar_opacity            0.0
yabai -m config mouse_modifier             fn
yabai -m config mouse_action1              move
yabai -m config mouse_action2              resize
yabai -m config mouse_drop_action          swap
yabai -m config layout                     bsp
yabai -m config top_padding                16
yabai -m config bottom_padding             16
yabai -m config left_padding               16
yabai -m config right_padding              16
yabai -m config window_gap                 10

yabai -m rule --add title="Preferences"         manage=off
yabai -m rule --add title=".*Preferences.*"     manage=off
yabai -m rule --add title="Settings"            manage=off
yabai -m rule --add title=".*Settings.*"        manage=off
yabai -m rule --add title="^Open.*$"            manage=off

yabai -m rule --add title="^Save.*"             manage=off
yabai -m rule --add title="^Export.*"           manage=off
yabai -m rule --add title="^Import.*"           manage=off
yabai -m rule --add title="^Print$"             manage=off
yabai -m rule --add title="^Share$"             manage=off
yabai -m rule --add title="^About.*"            manage=off
yabai -m rule --add title="^Rename.*"            manage=off

yabai -m rule --add app="^System Settings$"     manage=off
yabai -m rule --add app="^System Preferences$"  manage=off
yabai -m rule --add app="^System Information$"  manage=off
yabai -m rule --add app="^Archive Utility$"     manage=off
yabai -m rule --add app="^Calculator$"          manage=off
yabai -m rule --add app="^Dictionary$"          manage=off
yabai -m rule --add app="^Software Update$"     manage=off
yabai -m rule --add app="^Installer$"           manage=off
yabai -m rule --add app="^App Store$"           manage=off
yabai -m rule --add app="^Image Capture$"       manage=off
yabai -m rule --add app="^Stickies$"            manage=off
yabai -m rule --add app="^Activity Monitor$"    manage=off
yabai -m rule --add app="^Disk Utility$"        manage=off
yabai -m rule --add app="^Font Book$"           manage=off
yabai -m rule --add app="^Audio MIDI Setup$"    manage=off
yabai -m rule --add app="^Bluetooth File Exchange$" manage=off
yabai -m rule --add app="^Photo Booth$"         manage=off
yabai -m rule --add app="^Raycast$"             manage=off
yabai -m rule --add app="^Alfred$"              manage=off
yabai -m rule --add app="^1Password.*"          manage=off
yabai -m rule --add app="^Karabiner-Elements$"  manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off

yabai -m rule --add app="^Finder$"   title="(Co(py|nnect)|Move|Info|Pref)"  manage=off
yabai -m rule --add app="^Finder$"   title="^Get Info$"                     manage=off

yabai -m rule --add app="^Dock$"                manage=off
yabai -m rule --add app="^SystemUIServer$"      manage=off
yabai -m rule --add app="^SecurityAgent$"       manage=off
yabai -m rule --add app="^Spotlight$"           manage=off

yabai -m signal --add event=window_created \
    action='yabai -m query --windows --window $YABAI_WINDOW_ID \
              | jq -er ".subrole == \"AXDialog\" or .subrole == \"AXSystemDialog\"" \
              && yabai -m window $YABAI_WINDOW_ID --toggle float'

sbar_sig() {
    local event="$1" vars="$2"
    yabai -m signal --add event="$event" label="sbar_$event" \
        action="sketchybar --trigger yabai_$event $vars"
}

sbar_sig application_launched         'YABAI_PROCESS_ID=$YABAI_PROCESS_ID'
sbar_sig application_terminated       'YABAI_PROCESS_ID=$YABAI_PROCESS_ID'
sbar_sig application_front_switched   'YABAI_PROCESS_ID=$YABAI_PROCESS_ID YABAI_RECENT_PROCESS_ID=$YABAI_RECENT_PROCESS_ID'
sbar_sig application_activated        'YABAI_PROCESS_ID=$YABAI_PROCESS_ID'
sbar_sig application_deactivated      'YABAI_PROCESS_ID=$YABAI_PROCESS_ID'
sbar_sig application_visible          'YABAI_PROCESS_ID=$YABAI_PROCESS_ID'
sbar_sig application_hidden           'YABAI_PROCESS_ID=$YABAI_PROCESS_ID'

sbar_sig window_created               'YABAI_WINDOW_ID=$YABAI_WINDOW_ID'
sbar_sig window_destroyed             'YABAI_WINDOW_ID=$YABAI_WINDOW_ID'
sbar_sig window_focused               'YABAI_WINDOW_ID=$YABAI_WINDOW_ID'
sbar_sig window_moved                 'YABAI_WINDOW_ID=$YABAI_WINDOW_ID'
sbar_sig window_resized               'YABAI_WINDOW_ID=$YABAI_WINDOW_ID'
sbar_sig window_minimized             'YABAI_WINDOW_ID=$YABAI_WINDOW_ID'
sbar_sig window_deminimized           'YABAI_WINDOW_ID=$YABAI_WINDOW_ID'
sbar_sig window_title_changed         'YABAI_WINDOW_ID=$YABAI_WINDOW_ID'

sbar_sig space_created                'YABAI_SPACE_ID=$YABAI_SPACE_ID YABAI_SPACE_INDEX=$YABAI_SPACE_INDEX'
sbar_sig space_destroyed              'YABAI_SPACE_ID=$YABAI_SPACE_ID'
sbar_sig space_changed                'YABAI_SPACE_ID=$YABAI_SPACE_ID YABAI_SPACE_INDEX=$YABAI_SPACE_INDEX YABAI_RECENT_SPACE_ID=$YABAI_RECENT_SPACE_ID YABAI_RECENT_SPACE_INDEX=$YABAI_RECENT_SPACE_INDEX'

sbar_sig display_added                'YABAI_DISPLAY_ID=$YABAI_DISPLAY_ID YABAI_DISPLAY_INDEX=$YABAI_DISPLAY_INDEX'
sbar_sig display_removed              'YABAI_DISPLAY_ID=$YABAI_DISPLAY_ID'
sbar_sig display_moved                'YABAI_DISPLAY_ID=$YABAI_DISPLAY_ID YABAI_DISPLAY_INDEX=$YABAI_DISPLAY_INDEX'
sbar_sig display_resized              'YABAI_DISPLAY_ID=$YABAI_DISPLAY_ID YABAI_DISPLAY_INDEX=$YABAI_DISPLAY_INDEX'
sbar_sig display_changed              'YABAI_DISPLAY_ID=$YABAI_DISPLAY_ID YABAI_DISPLAY_INDEX=$YABAI_DISPLAY_INDEX YABAI_RECENT_DISPLAY_ID=$YABAI_RECENT_DISPLAY_ID YABAI_RECENT_DISPLAY_INDEX=$YABAI_RECENT_DISPLAY_INDEX'

sbar_sig mission_control_enter        'YABAI_MISSION_CONTROL_MODE=$YABAI_MISSION_CONTROL_MODE'
sbar_sig mission_control_exit         'YABAI_MISSION_CONTROL_MODE=$YABAI_MISSION_CONTROL_MODE'
sbar_sig dock_did_change_pref         ''
sbar_sig dock_did_restart             ''
sbar_sig menu_bar_hidden_changed      ''

echo "yabai configuration loaded.."
