#!/bin/bash
set -eu

options=(
  style=round
  width=5.0
  hidpi=on
  active_color='gradient(top_left=0xff79c0ff,bottom_right=0xffb4d3ff)'
  inactive_color=0x6630383f
  background_color=0x00000000
  blacklist='System Settings,Login Window,Notification Center,Control Center'
)

borders "${options[@]}"
